<?php
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\routing\routeMatchInterface;

/**
 *  Implements hook_help()
 */

function twllc_world_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.twllc_world':
      $output ='';
      $output .= '<H3>' . t('About') . '</H3>' ;
      $output .= '<p>' . t('This is an example module') . '</p>';
      return $output;
    
    default:
  }
}
/**
 * Implements hook_mail().
 */
function twllc_world_mail($key, &$message, $params) {
  switch ($key) {
    case 'twllc_world_log':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('There is an error on your website');
      $message['body'][] = $params['message'];
      $user_message = 'The user that was logged in: [current-user:name].';
      $message['body'][] = \Drupal::token()->replace($user_message, ['current-user' => \Drupal::currentUser()]);

      break;
  }
}
/**
 * Implements hook_mail_alter().
 */
function twllc_world_mail_alter(&$message) {
  switch ($message['key']) {
    case 'twllc_world_log':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      break;
  }
}

/**
 * Implements hook_token_info().
 */
function twllc_world_token_info() {
  $type = [
    'name' => t('Twllc World'),
    'description' => t('Tokens related to the Twllc World module.'),
  ];

  $tokens['salutation'] = [
    'name' => t('Salutation'),
    'description' => t('The Twllc World salutation value.'),
  ];

  return [
    'types' => ['twllc_world' => $type],
    'tokens' => ['twllc_world' => $tokens],
  ];
}

/**
 * Implements hook_tokens().
 */
function twllc_world_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  if ($type == 'twllc_world') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'salutation':
          $replacements[$original] = \Drupal::service('twllc_world.salutation')->getSalutation();
          $config = \Drupal::config('twllc_world.custom_salutation');
          $bubbleable_metadata->addCacheableDependency($config);
          break;

      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_theme().
 */
function twllc_world_theme($existing, $type, $theme, $path) {
  return [
    'twllc_world_salutation' => [
      'variables' => [
        'salutation' => NULL,
        'target' => NULL,
        'overridden' => FALSE,
      ],
    ],
  ];
}

/**
 * Default preprocessor function for the twllc_world_salutation theme hook.
 */
function template_preprocess_twllc_world_salutation(&$variables) {
  $variables['attributes'] = [
    'class' => ['salutation'],
  ];
}


/**
 * Implements hook_theme_suggestions_HOOK().
 */
function twllc_world_theme_suggestions_twllc_world_salutation($variables) {
  $suggestions = [];

  if ($variables['overridden'] === TRUE) {
    $suggestions[] = 'twllc_world_salutation__overridden';
  }

  return $suggestions;
}