<?php

use Drupal\Core\routing\routeMatchInterface;

/**
 *  Implements hook_help()
 */

function freehk_world_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.freehk_world':
      $output ='';
      $output .= '<H3>' . t('About') . '</H3>' ;
      $output .= '<p>' . t('This is a Free Hong Kong module') . '</p>';
      return $output;
    
    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */

function freehk_world_form_salutation_configuration_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['terms_of_user'] = array (
    '#type' => 'checkbox',
    '#title' => t("I agree with the website's terms and conditions."),
    '#required' => TRUE,
  );
}